version: '3.8'

services:
  latex:
    build: .
    container_name: latex-devcontainer
    volumes:
      - ./:/workspace    
    command: sleep infinity
    enviroment: 
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
